import type { Course } from "./types" // This import should be relative within lib

export const courses: Course[] = [
  {
    id: "1",
    title: "Introduction to Web Design",
    instructor: "Jane Doe",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 75,
    isEnrolled: true,
    isFavorite: true,
    category: "Design",
  },
  {
    id: "2",
    title: "Advanced JavaScript Concepts",
    instructor: "John Smith",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 30,
    isEnrolled: true,
    isFavorite: false,
    category: "Development",
  },
  {
    id: "3",
    title: "UI/UX Design Principles",
    instructor: "Emily White",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 0,
    isEnrolled: false,
    isFavorite: true,
    category: "Design",
  },
  {
    id: "4",
    title: "React.js for Beginners",
    instructor: "Michael Brown",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 0,
    isEnrolled: false,
    isFavorite: false,
    category: "Development",
  },
  {
    id: "5",
    title: "Data Science with Python",
    instructor: "Sarah Green",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 90,
    isEnrolled: true,
    isFavorite: true,
    category: "Data Science",
  },
  {
    id: "6",
    title: "Digital Marketing Fundamentals",
    instructor: "David Lee",
    imageUrl: "/placeholder.svg?height=180&width=320",
    progress: 0,
    isEnrolled: false,
    isFavorite: false,
    category: "Marketing",
  },
]
